version: '3.8'
services:
  grafana:
    restart: 'always'
    image: grafana/grafana
    container_name: grafana-container
    network_mode: 'host'
    volumes:
     - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  prometheus:
    restart: 'always'
    image: prom/prometheus
    container_name: prometheus-container
    network_mode: 'host'
    command:
    - '--config.file=/prometheus/config/prometheus.yaml'
    volumes:
    - ./prometheus:/prometheus/config
    # depends_on:
    # - mongo_exporter
