global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: web-server
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['localhost:8080']
  - job_name: mongodb
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
    - targets: ['localhost:9216']
