{
 "title": "NodeJS Request Flow Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Node request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Request Duration Summary",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_ms_bucket[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 300 ms",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (app) (increase(http_request_duration_ms_bucket{le=\"300\"}[1d])) / sum by (app) (increase(http_request_duration_ms_count[1d]))) * 100"
    }
   ]
  },
  {
   "title": "Node - Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count[2m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Node Reqeust Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(sum by (le) (increase(http_request_duration_ms_bucket[1d])), \"le\", \"Inf\", \"le\", \"\\\\+Inf\")",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Percentage of requests shorter than 300 ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(sum (rate(http_request_duration_ms_bucket{le=\"0.3\"}[2m])) / sum(rate(http_request_duration_ms_count[2m]))) * 100"
    }
   ]
  },
  {
   "title": "Node Request Duration (Stacked All Buckets)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_ms_bucket[3m]))\n",
     "legendFormat": "Requests > {{le}}s per ms"
    }
   ]
  },
  {
   "title": "Node Request Duration (Unstacked Buckets)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_request_duration_ms_bucket{le=\"10\"}[3m])) - sum (rate(http_request_duration_ms_bucket{le=\"50\"}[3m]))",
     "legendFormat": "10  <  t  <  50"
    },
    {
     "expr": "sum (rate(http_request_duration_ms_bucket{le=\"50\"}[3m])) - sum (rate(http_request_duration_ms_bucket{le=\"100\"}[3m]))",
     "legendFormat": "50  <  t  <  100"
    },
    {
     "expr": "sum (rate(http_request_duration_ms_bucket{le=\"100\"}[3m])) - sum (rate(http_request_duration_ms_bucket{le=\"200\"}[3m]))",
     "legendFormat": "100  <  t  < 200"
    },
    {
     "expr": "sum (rate(http_request_duration_ms_bucket{le=\"200\"}[3m])) - sum (rate(http_request_duration_ms_bucket{le=\"300\"}[3m]))",
     "legendFormat": "200  <  t  <  300"
    },
    {
     "expr": "sum (rate(http_request_duration_ms_bucket{le=\"300\"}[3m])) - sum (rate(http_request_duration_ms_bucket{le=\"500\"}[3m]))",
     "legendFormat": "300  <  t  <  500"
    },
    {
     "expr": "sum (rate(http_request_duration_ms_bucket{le=\"500\"}[3m])) - sum (rate(http_request_duration_ms_bucket{le=\"800\"}[3m]))",
     "legendFormat": "500  <  t  <  800"
    },
    {
     "expr": "sum (rate(http_request_duration_ms_bucket{le=\"+Inf\"}[3m])) - sum (rate(http_request_duration_ms_bucket{le=\"10\"}[3m]))",
     "legendFormat": "10  <  t"
    }
   ]
  },
  {
   "title": "Node Request Duration (Stacked Buckets)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_ms_count[3m]) - ignoring (le) group_right rate(http_request_duration_ms_bucket{le!=\"+Inf\"}[3m]))",
     "legendFormat": "Requests > {{le}}s per ms"
    }
   ]
  }
 ]
}